title: DI
lang: es
description: Desarrollo de Interfaces (2ºDAM)
remote_theme: rundocs/jekyll-rtd-theme

translate:
 note: info
 search: buscar
 warning: destacado
 search_docs: buscar..
 searching: buscando
 not_found: No encontrado
 search_results_found: Resultados Encontrados
 this: este
 is_under_the_terms_of: esta_bajo_los_terminos_de

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

